language: php
php:
  - 7.2
before_script:
  - composer -v update
#  - mysql -e "create database IF NOT EXISTS phpci_tmcms_empty;"
script:
  - phpunit --debug --verbose --colors --bootstrap vendor/devp-eu/tmcms-tests/src/phpunit_bootstrap.php vendor/devp-eu/tmcms-tests/src/
